
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Liqiang He
tagline: Software Engineer/Machine Learning Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: helq2612@gmail.com
phone: 541 740 4022
#website: blog.webjeda.com #do not add http://
linkedin: https://www.linkedin.com/in/he-liqiang-a64656b6/
github: https://helq2612.github.io/
#twitter: '@webjeda'

#Update all the sections by editing the files inside _includes folder.
